export const environment = {
  production: true,
  transporteUrl: 'http://onusstate.com:8080/transporte',
  porteUrl: 'http://onusstate.com:8080/porte',
  provinciaUrl: 'http://onusstate.com:8080/provincia',
  paisUrl: 'http://onusstate.com:8080/pais',
  authURL : 'http://onusstate.com:8080/auth/',
  conductorUrl : 'http://onusstate.com:8080/conductor',
  expediorUrl : 'http://onusstate.com:8080/expedidor',
  emailUrl:'http://onusstate.com:8080/email',
  registroExternos:'http://onusstate.com/singup-externos',
  confirmacion:'http://onusstate.com/confirmacion',
  usuarioUrl:'http://onusstate.com:8080/usuario',
  cuentaBancariaUrl:'http://onusstate.com:8080/cuentaBancaria',
  tipoCamionUrl:'http://onusstate.com:8080/tipoCamion',
  tipoRemolqueUrl:'http://onusstate.com:8080/tipoRemolque',
  camionUrl:'http://onusstate.com:8080/camion',
  remolqueUrl:'http://onusstate.com:8080/remolque',
  estadoUrl:'http://onusstate.com:8080/estado',
  viajeUrl:'http://onusstate.com:8080/viaje',
  pagoUrl:'http://onusstate.com:8080/pago',
  estadoPagoUrl:'http://onusstate.com:8080/estadoPago',
  notificacionUrl:'http://onusstate.com:8080/notificacion',
  gravedadUrl:'http://onusstate.com:8080/gravedad',
  recaptcha: {
    siteKey: '6LcozHIgAAAAAJd4iyKyVrKu6w3drShtMQsXq2p2',
  },
};
